config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'pages#home'

  resources :pharmacies, only: [ :index ]
  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'
  post 'new_contact', to: 'pages#new_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :pharmacy, presence: true
  validates :email, presence: true
  validates :phone, presence: true
  validates :message, presence: true
end

app/models/pharmacy.rb
class Pharmacy < ApplicationRecord
  mount_uploader :image, PhotoUploader
  validates :name, presence: true
  validates :opening_times, presence: true
  validates :url, presence: true
  validates :street, presence: true
  validates :zip_code, presence: true
  validates :city, presence: true

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    "#{street}, #{zip_code} #{city}"
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, PhotoUploader
  validates :image, presence: true
end

app/models/quote.rb
class Quote < ApplicationRecord
  mount_uploader :image, PhotoUploader
  validates :content, presence: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_raven_context

  def default_url_options
  { host: ENV["HOST"] || "localhost:3000" }
  end

  private

  def set_raven_context
    Raven.user_context(id: session[:current_user_id]) # or anything else in session
    Raven.extra_context(params: params.to_unsafe_h, url: request.url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @products = Product.all
    @quotes = Quote.limit(2).order("id desc")
  end

  def about; end

  def contact; end

  def new_contact
    @contact = set_contact
    if @contact.save && verify_recaptcha(model: @contact)
      flash[:notice] = "Votre message a bien été enregistré.
                        Nous allons prendre contact avec vous rapidement."
      ContactMailer.new_message(@contact).deliver_now
      redirect_to root_path
    else
      flash[:notice] = "Tous les champs doivent être complétés"
      render :contact
    end
  end

  private

  def set_contact
    contact = Contact.new
    params.permit(:pharmacy, :email, :phone, :message)
    contact.pharmacy = params[:pharmacy]
    contact.email = params[:email]
    contact.phone = params[:phone]
    contact.message = params[:message]
    contact
  end
end

app/controllers/pharmacies_controller.rb
class PharmaciesController < ApplicationController
  def index
    define_pharmacies
    @hash = Gmaps4rails.build_markers(@pharmacies) { |pharmacie, marker|
      set_marker(pharmacie, marker)
    }
  end

  private

  def define_pharmacies
    if params[:address].present?
      address = params[:address]
      @pharmacies = Pharmacy.where.not(latitude: nil, longitude: nil).near(address, 10)
    else
      @pharmacies = Pharmacy.all
    end
  end

  def set_marker(pharmacie, marker)
    marker.lat pharmacie.latitude
    marker.lng pharmacie.longitude
    marker.infowindow marker.infowindow render_to_string(partial: "/shared/map-infowindow",
                                                         locals: { pharmacy: pharmacie })
    marker.json(id: pharmacie.id)
    marker.picture(
      url: ActionController::Base.helpers.asset_path("map_locator4.png"),
      width: 33,
      height: 49,
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Clic & Prix - Trouvez une pharmacie à coté de chez vous</title>
    <meta name="description" content="Oubliez la queue en pharmacie, envoyez votre ordonnance en photo, venez la chercher 2 heures après.">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
  </head>
  <body>
    <!--<!-%=render 'shared/navbar' %>-->
    <%= render 'shared/flashes' %>
    <%= yield %>

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?componentRestrictions=:fr&libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/OverlappingMarkerSpiderfier/1.0.3/oms.min.js" %>
    <%= javascript_include_tag "application" %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about">
  <div class="home home__background" style="background-image: linear-gradient(-45deg, #FED63E 50%, #FFED72 100%);">
    <%= render 'shared/header' %>
    <div class="home__baseline">
      <div id="background-square-about" style="background-image: url('<%= image_url "background_element.png" %>')">
        <div class="home__landing-content">
          <h2 class="about-title">Qui sommes-nous ?</h2>
        </div>
      </div>
    </div>
  </div>
  <div class="presentation">
<!--       <%= image_tag "logo.png", class: "mb+" %> -->
      <p class="pt"><span>Clic & Prix</span> renouvelle l’expérience client en pharmacie</p>
      <p class="pt"><span>Clic & Prix</span> est une Start up de communication, Marketing et digital pour les pharmacies.<br>Nous sommes basés sur Marseille.</p>
      <p class="pt"><span>Clic & Prix</span> est un nouveau service proposé aux pharmaciens mettant le digital au service de l’expérience client en pharmacie, <span>Clic & Prix</span> a pour but d’enrichir le lien entre patient et pharmacien.</p>
      <p class="pt">A l’origine de <span>Clic & Prix</span>, une volonté de relever un double défi :
        <ul>
          <li>Donner l’accessibilité sur tous les supports et pour tous les patients,
          </li>
          <li>Apporter la même expérience à tous et sur tout le territoire
          </li>
        </ul>
      </p>
      <p class="pt"><span>Clic & Prix</span> est un mini-site personnalisé agrée au nom de la pharmacie qui vous permet :
        <ul>
          <li>D’envoyer une photo de votre ordonnance afin de préparer vos médicaments en amont de votre visite,</li>
          <li>D’accéder à une messagerie partagée avec le pharmacien,</li>
          <li>De bénéficier d’avantages exclusifs sur des produits de parapharmacie et OTC,</li>
          <li>D’accéder aux informations de base de la pharmacie : coordonnées, horaires d’ouverture, plan d’accès.</li>
        </ul>
      </p>
      <p class="pt"><span>Clic & Prix</span> et également un dispositif en officine afin d’améliorer la qualité de la relation et du service rendu :
        <ul>
          <li>Un comptoir en pharmacie vous est dédié,</li>
          <li>Le pharmacien vous attend,</li>
          <li>Vous récupérez votre commande en 2 h et sans faire la queue,</li>
          <li>Des échantillons et des cadeaux sont glissés avec votre commande dans un emballage Clic et Prix.</li>
        </ul>
      </p>
      <p class="pt mb+">La santé se vie aussi en gagnant du temps … Vivez l’expérience !</p>
      <%= image_tag "picture_about.jpg", class: "picture-about" %>





  </div>
</div>
<%= render 'shared/footer' %>

app/views/pages/contact.html.erb
<div class="contact" style="background-image: linear-gradient(-180deg, #FFFEFB 0%, #FFFCF0 100%);">
  <div class="pt-- pl--">
    <%= link_to root_path do %>
      <%= image_tag "logo.png" %>
    <% end %>
  </div>
  <h2 class="pt- text-center">Vous êtes pharmacien titulaire ?</h2>
  <p class="text-center">Vous souhaitez faire bénéficier à vos clients du service digital Clic & Prix</p>
  <p class="text-center pt+ mt">Contactez-nous ou appelez-nous au 09 67 20 30 64</p>

<form action="<%= new_contact_path %>" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2 col-md-6 col-md-offset-3"  style="margin-top: 15px;">
      <input placeholder="Votre pharmacie" name="pharmacy" class="form-control form-contact" autofocus='true' value="<%= params[:pharmacy]%>">
    </div>

    <div class="col-xs-8 col-xs-offset-2 col-md-6 col-md-offset-3"  style="margin-top: 15px;">
      <input placeholder="Votre email" name="email" class="form-control form-contact" autofocus='true' value="<%= params[:email]%>">
    </div>

    <div class="col-xs-8 col-xs-offset-2 col-md-6 col-md-offset-3"  style="margin-top: 15px;">
      <input placeholder="Votre numéro de téléphone" name="phone" class="form-control form-contact" autofocus='true' value="<%= params[:phone]%>">
    </div>

     <div class="col-xs-8 col-xs-offset-2 col-md-6 col-md-offset-3"  style="margin-top: 15px;">
      <textarea placeholder="Votre message" name="message" class="form-control form-contact text-area-size" autofocus='true' value="<%= params[:message]%>"></textarea>
    </div>

    <div class="col-xs-8 col-xs-offset-2 col-md-6 col-md-offset-3"  style="margin-top: 15px;">
          <%= recaptcha_tags %>
    </div>

    <div class="col-xs-6 col-xs-offset-3"  style="margin-top: 15px;text-align: center;">
      <input type="submit" class="btn btn-primary btn-lg mt mb cp-button" value="Envoyer">
    </div>

    </div>
</form>

</div>

app/views/pages/home.html.erb
<div class="container p0 m0">
  <div class="home home__background" style="background-image: linear-gradient(-45deg, #FED63E 50%, #FFED72 100%);">
    <%= render 'shared/header' %>
    <div class="home__baseline">
      <%= image_tag "Smartphone.png", id: "smartphone", class: "hidden-xs" %>
      <div id="background-square" style="background-image: url('<%= image_url "background_element.png" %>')">
        <div class="home__landing-content">
          <h1>OUBLIEZ LA QUEUE EN PHARMACIE</h1>
          <h2>Envoyez votre ordonnance en photo,<br>retrait express de votre commande en 2 heures !</h2>
          <div class="pt+ mt">
            <p>Trouvez une pharmacie près de chez vous</p>
            <%= render 'shared/research-button' %>
          </div>
        </div>
      </div>
    </div>
    <div class="home__how-works" style="background-image: linear-gradient(-180deg, #FFFEFB 0%, #FFFCF0 100%);">
      <h2 class="text-center">COMMENT ÇA MARCHE ? </h2>
      <p class="text-center padding">Simple comme trois clics</p>
      <div class="container">
        <div class="row">
          <div class="col-md-3 col-xs-12">
            <div class="polygon-demo" style="background-image: url('<%= image_url "polygon.png" %>')">
              <div class="polygon-demo--width">
                <%= image_tag "icon_smartphone.png", id:"icon_smartphone" %>
                <h2 class="text-center">Cherchez une pharmacie</h2>
              </div>
            </div>
            <p class="text-center pt">Trouvez la pharmacie Clic et Prix la plus proche de chez vous en 1 clic</p>
          </div>
          <div class="hidden-sm hidden-xs col-md-1 next-step">
            <%= image_tag "next.png", class:"align-middle" %>
          </div>
          <div class="col-md-3 col-xs-12">
            <div class="polygon-demo" style="background-image: url('<%= image_url "polygon.png" %>')">
              <div class="polygon-demo--width">
                <%= image_tag "icon_photo-camera.png", id:"icon_photo-camera" %>
                <h2 class="text-center">Envoyez votre ordonnance en photo</h2>
              </div>
            </div>
            <p class="text-center pt">Prenez et envoyez votre ordonnance en photo en 2 clics</p>
          </div>
          <div class="hidden-sm hidden-xs col-md-1 next-step">
            <%= image_tag "next.png", class:"align-middle" %>
          </div>
          <div class="col-xs-12 col-md-3">
            <div class="polygon-demo" style="background-image: url('<%= image_url "polygon.png" %>')">
              <div class="polygon-demo--width">
                <%= image_tag "icon_drugs.png", id:"icon_drugs" %>
                <h2 class="text-center">Récuperez votre commande</h2>
              </div>
            </div>
            <p class="text-center pt">Votre pharmacien vous attend, n’oubliez pas de venir avec l’original de votre ordonnance et carte vitale</p>
          </div>
        </div>
      </div>
    </div>
    <div class="home__products">
      <h2 class="text-center">UNE SÉLECTION DE PRODUITS À NE PAS MANQUER</h2>
      <p class="text-center mb">Des produits avec une remise immédiate en caisse.</p>
      <div class="carrousel-container">
        <div class="span8 welcome-image">
          <div id="myCarousel" class="carousel slide col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3" data-ride="carousel">
          <!-- Carousel items -->
            <div class="carousel-inner" role="listbox">
              <% @products.each_with_index do |product, index| %>
                  <div class="<%= "active" if index == 0 %> item">
                  <%= cl_image_tag product.image, height: 459, width: 699, crop: :fill %>
                  </div>
              <% end %>
            </div>
              <!-- Carousel nav -->
            <a class="carousel-control left car-nav" href="#myCarousel" data-slide="prev">&lsaquo;</a>
            <a class="carousel-control right car-nav" href="#myCarousel" data-slide="next">&rsaquo;</a>

              <!-- LINKED NAV -->
            <div class="text-center">
              <ol class="carousel-linked-nav pt carousel-indicators">
                <% @products.each_with_index do |product, index| %>
                    <li data-target="#myCarousel" data-slide-to="<%= index %>" <%= "class=active" if index == 0 %>><i class="fa fa-circle" aria-hidden="true"></i></a>
                    </li>
                <% end %>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="home__testimonials" style="background-image: linear-gradient(-180deg, #FFFEFB 0%, #FFFCF0 100%);">
      <h2 class="text-center">ILS PARLENT DE CLIC & PRIX</h2>
      <div class="container pt+">
        <div class="row">
          <% @quotes.each_with_index do |quote, index| %>
            <div class="col-xs-12 col-sm-4 <%= "col-sm-offset-2" if index == 0  %>">
              <div class="testimonials-background">
                <%= image_tag "quote.png", class:"testimonials-quote" %>
                <%= cl_image_tag quote.image, height: 100, width: 100, crop: :fill, class:"testimonials-image" %>
                <p class="padding"><%= quote.content %></p>
                <p class="testimonials-people pl"><%= quote.name %><strong> <%= quote.title.downcase %></strong></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="home__start-now" style="background-image: linear-gradient(-45deg, #FED63E 50%, #FFED72 100%);">
      <h2 class="text-center pt+">COMMENCEZ L'EXPERIENCE</h2>
      <p class="text-center">Trouvez une pharmacie près de chez vous.</p>
      <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 padding">
        <%= render 'shared/research-button' %>
      </div>
    </div>
    <div class="home__about pb">
      <h2 class="text-center pt-">LES AVANTAGES</h2>
      <p class="text-center">Le service de l’experience en pharmacie.</p>
      <div class="container pt-">
        <div class="row">
          <div class="col-xs-12 col-md-4 about--container">
            <div class="picto-container">
              <%= image_tag "icon-Advantages.png" %>
            </div>
            <h3 class="text-center pt pb">SIMPLICITÉ</h3>
            <div>
              <p><i class="fa fa-check" aria-hidden="true"></i> Pas d’application à télécharger</p>
              <p><i class="fa fa-check" aria-hidden="true"></i> Accessible sur tous supports</p>
            </div>
          </div>
          <div class="col-xs-12 col-md-4 about--container">
            <div class="picto-container">
              <%= image_tag "icon-time.png" %>
            </div>
            <h3 class="text-center pt pb">RAPIDITÉ</h3>
            <div>
              <p><i class="fa fa-check" aria-hidden="true"></i> Envoyer votre ordonnance en photo</p>
              <p><i class="fa fa-check" aria-hidden="true"></i> Retrait express en 2h</p>
            </div>
          </div>
          <div class="col-xs-12 col-md-4 about--container">
            <div class="picto-container">
              <%= image_tag "icon-exclu.png" %>
            </div>
            <h3 class="text-center pt pb">EXCLUSIVITÉ</h3>
            <div>
              <p><i class="fa fa-check" aria-hidden="true"></i> Fini la queue en pharmacie</p>
              <p><i class="fa fa-check" aria-hidden="true"></i> Un service premium</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </div>
</div>

app/views/pharmacies/index.html.erb
<div class="result-container">
  <div class="results">
    <div class="results__search-bar" style="background-image: linear-gradient(-45deg, #FED63E 50%, #FFED72 100%);">
      <div class="pt-- pl--">
        <%= link_to root_path do %>
          <%= image_tag "logo.png" %>
        <% end %>
      </div>
      <p class="padding">Envoyez une photo de votre ordonnance, retrait express de votre commande en 2 heures !</p>
      <!-- search button for large screen -->
      <div class="pl25 pt pr hidden-xs">
        <%= render 'shared/research-button' %>
      </div>
      <!-- search button for small screen -->
      <div class="hidden-sm hidden-md hidden-lg">
        <%= render 'shared/research-button-mobile' %>
      </div>
    </div>
    <div class="results__list" style="background-image: linear-gradient(-180deg, #FFFEFB 0%, #FFFCF0 100%);">
      <% if @pharmacies.empty? %>
        <p class="pl25 pt">Il n'y pas de pharmacies Clic & Prix proche de chez vous.</p>
      <% else %>
        <p class="pl25 pt">Les pharmacies Clic & Prix proches de chez vous <% if @pharmacies.to_a.count == 1 %>
          (<%= @pharmacies.to_a.count %> résultat) :
          <% else %>
         (<%= @pharmacies.to_a.count %> résultats) :</p>
         <% end %>
      <% end %>
      <div class="card-container pt pl- pr- ">
        <% @pharmacies.each do |pharmacy| %>
          <%= render 'shared/card', pharmacy: pharmacy %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="hidden-xs map-container">
    <div id="map" style="width: 100%; height: 100vh;"></div>
  </div>
</div>


<% content_for(:after_js) do %>
  <script type="text/javascript">

    var mapOptions = {
      center: new google.maps.LatLng(46.52863469527167,2.43896484375),
      minZoom: 6,
      maxZoom: 18,
    };

    var handler = Gmaps.build('Google');
    handler.buildMap({
      provider:  mapOptions,
      internal: { id: 'map' },
    },


    function() {

      markers = <%= raw @hash.to_json %>


      Gmaps.store = {}

      Gmaps.store.markers = markers.map(function(m) {
          marker = handler.addMarker(m);
          marker.serviceObject.set('id', m.id);
          return marker;
      });

      var oms = new OverlappingMarkerSpiderfier(handler.getMap(), {
          keepSpiderfied: true,
          markersWontMove: true,
          markersWontHide: true,
          basicFormatEvents: true,
        });

      _.each(Gmaps.store.markers, function(marker){

        oms.addMarker(marker.getServiceObject());

        google.maps.event.addListener(marker.getServiceObject(), 'click', function(){

          var id = marker.serviceObject.id;

          $(".card").removeClass("is-clicked");
          $('#pharmacy-'+id).addClass("is-clicked");
          $('html, body').animate({
            scrollTop: $('#pharmacy-'+id).offset().top - 250
          }, 500);
        });

        var id = marker.serviceObject.id;

        $('#pharmacy-'+id).click(function(){
            $(".card").removeClass("is-clicked");
            $(this).addClass("is-clicked");
            google.maps.event.trigger(marker.getServiceObject(), 'click');

            // marker.serviceObject.setAnimation(google.maps.Animation.BOUNCE);
            // setTimeout(function(){ marker.serviceObject.setAnimation(null); }, 750);
        });

      });

      handler.bounds.extendWith(Gmaps.store.markers);
      handler.fitMapToBounds();

      if (markers.length == 0) {
        handler.getMap().setZoom(4);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(16);
      }
    });



  </script>
<% end %>

app/views/shared/_card.html.erb
<div class="card" id="pharmacy-<%= pharmacy.id %>">
  <div class="card__content pt pl">
    <p class="card-title"><%= pharmacy.name  %></p>
    <p>
      <i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp <%= "#{pharmacy.street}, #{pharmacy.zip_code}, #{pharmacy.city}" %>
    </p>
    <p>
      <i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp<%= pharmacy.opening_times %>
    </p>
    <% unless pharmacy.opening_times_second.nil? %>
      <% unless pharmacy.opening_times_second.empty? %>
        <p>
          <i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp<%= pharmacy.opening_times_second %>
        </p>
      <% end %>
    <% end %>
    <% unless pharmacy.opening_times_third.nil?  %>
      <% unless pharmacy.opening_times_third.empty?  %>
        <p>
          <i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp<%= pharmacy.opening_times_third %>
        </p>
      <% end %>
    <% end %>
    <% unless pharmacy.phone_number.nil? %>
      <% unless pharmacy.phone_number.empty? %>
        <p>
          <i class="fa fa-phone" aria-hidden="true"></i>&nbsp<%= pharmacy.phone_number %>
        </p>
      <% end %>
    <% end %>
    <div class="pt-- padding-bottom-button">
      <a href="<%= pharmacy.url %>" class="order-button">Commander dans cette pharmacie</a>
    </div>
  </div>
  <% if pharmacy.image.present? %>
    <div class="card__picture hidden-xs hidden-sm">
      <%= cl_image_tag pharmacy.image, height: 150, width: 214, crop: :fill %>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer" style="background-image: linear-gradient(-180deg, #FFFCF0 0%, #FFFEFB 100%);">
  <div class="about-cp">
    <ul class="list-unstyled">
      <li class="pb--"><%= link_to "Vous êtes une pharmacie ? Devenez partenaire", contact_path %></li>
      <li class="pb--"><%= link_to "A propos de Clic & Prix", about_path %></li>
      <li class="pb--">Termes et conditions</li>
    </ul>
    <p class="pt">© Clic&Prix 2017 - Tous droits réservés</p>

  </div>
  <div>
    <ul class="list-unstyled">
      <li class="pb--"><%= link_to( "Trouver une pharmacie à Marseille", pharmacies_path(address: "Marseille")) %></li>
      <li class="pb--"><%= link_to( "Trouver une pharmacie à Perpignan", pharmacies_path(address: "Perpignan")) %></li>
      <li class="pb--"><%= link_to( "Trouver une pharmacie à Orange", pharmacies_path(address: "Orange")) %></li>
      <li class="pb--"><%= link_to( "Trouver une pharmacie à Béziers", pharmacies_path(address: "Béziers")) %></li>
      <li class="pb--"><%= link_to( "Trouver une pharmacie à Narbonne", pharmacies_path(address: "Narbonne")) %></li>
    </ul>
  </div>
  <div class="pr+ mr+ social-links pt+">
    <p class="hidden-xs">Retrouvez nous sur les réseaux sociaux</p>
    <ul class="list-inline text-center">
      <li> <a href="https://www.facebook.com/EmergenceDev/">
        <i class="fa fa-linkedin-square fa-lg" aria-hidden="true"></i></a></li>
      <li><a href="https://www.linkedin.com/company/5246248/"><i class="fa fa-facebook-square fa-lg" aria-hidden="true"></i></a></li>
    </ul>
    <div class="pt">
      <p>2 Rue Odette Jasse • 13015 Marseille</p>
      <p><a href="tel:0967203064">Tél : 09 67 20 30 64</a></p>
      <p><a href="mailto:clicetprixpharmacie@gmail.com">Mail : clicetprixpharmacie@gmail.com</a></p>
    </div>
  </div>
</div>


</div>

app/views/shared/_header.html.erb
<div class="home__header">
  <div class="pt-- pl-- logo">
    <%= link_to root_path do %>
      <%= image_tag "logo.png" %>
    <% end %>
  </div>
  <div class="header-navigation">
    <%= link_to about_path do %>
      <p class="pr hidden-xs">A propos  </p>
    <% end %>
    <%= link_to contact_path do %>
      <p class="pr hidden-xs">Devenir pharmacie partenaire </p>
    <% end %>
  </div>
</div>

app/views/shared/_research-button-mobile.html.erb
<form action="<%= pharmacies_path %>" class="research-button-mobile">
  <div class="search-input">
    <i class="fa fa-map-marker" aria-hidden="true"></i>
    <input type="text" placeholder="Ville, rue, code postal ..." name="address" autofocus='true' value="<%= params[:address]%>" class="search-field-mobile pharmacy-lookup">
  </div>
  <input type="submit" value="Chercher" class="cta-mobile">
</form>

app/views/shared/_research-button.html.erb
<form action="<%= pharmacies_path %>" class="research-button">
  <i class="fa fa-map-marker" aria-hidden="true"></i>
  <input type="text" placeholder="Ville, rue, code postal ..." name="address" autofocus='true' value="<%= params[:address]%>" class="search-field pharmacy-lookup">
  <input type="submit" value="Chercher" class="cta">
</form>